### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid.

### ISSUE THREAD

**Issue by 2xsaiko** [poudink/Plastik#16]
Running gtk-update-icon-cache on the icon theme causes it to error:

    % gtk-update-icon-cache ~/.local/share/icons/crystalsvg 
    gtk-update-icon-cache: The generated cache was invalid.

I have no idea what this does or why it fails, but it prevents me from installing this as a system-wide package on NixOS since it runs this command on all selected icon themes.

**Comment by poudink** [comment]
this should be fixed by https://github.com/poudink/Plastik/commit/193f6847674453dfee76d3c7d2f511612ec41519?

**Comment by 2xsaiko** [comment]
It is. Thanks!
