### ISSUE TITLE
Change link to qt6 port of styleplugins

### ISSUE THREAD

**Issue by MartinF99** [poudink/Plastik#25]
I currently do not work on porting all qstyleplugins to qt6 anymore, instead I only work on Plastikstyle, (just the plastikpart).
So instead of linking to https://github.com/MartinF99/qtstyleplugins link to https://github.com/MartinF99/PlastikStyle/

**Comment by MartinF99** [comment]
oh I just saw you're already linking to PlastikStyle. I still recommend removing the qstyleplugins-qt6 link

**Comment by poudink** [comment]
alright
